"""Export the design tokens for the non-Python figure pipelines.

Writes:
  * tools/figstyle/tokens.json   — language-neutral dump (anything can read)
  * diagrams/tokens.mjs          — ES module for the JS slide-diagram engine
    (diagrams/engine.mjs should import its palette from here instead of its
    own drifted copy — see docs/figure-style-guide.md §Pipelines)

Run:  python3 -m figstyle.export        (from tools/, or via tools on sys.path)
"""

from __future__ import annotations

import json
import os

from . import tokens as T

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def as_dict() -> dict:
    return {
        "neutrals": {
            "ink": T.INK, "muted": T.MUTED, "faint": T.FAINT,
            "hairline": T.HAIRLINE, "panel": T.PANEL, "paper": T.PAPER,
            "noveltyFill": T.NOVELTY_FILL, "containerFill": T.CONTAINER_FILL,
            "insetFill": T.INSET_FILL,
        },
        "accents": {name: {"tint": a.tint, "base": a.base, "dark": a.dark}
                    for name, a in T.ACCENTS.items()},
        "roles": {role: name for role, name in
                  ((r, next(n for n, a in T.ACCENTS.items() if a is acc))
                   for r, acc in T.ROLE.items())},
        "cycle": T.CYCLE,
        "type": {
            "sans": T.FONT_SANS, "mono": T.FONT_MONO,
            "title": T.FS_TITLE, "label": T.FS_LABEL,
            "small": T.FS_SMALL, "tiny": T.FS_TINY, "min": T.FS_MIN,
            "letterspaceCaps": T.LETTERSPACE_CAPS,
        },
        "stroke": {"hair": T.SW_HAIR, "box": T.SW_BOX, "line": T.SW_LINE,
                   "heavy": T.SW_HEAVY, "halo": T.SW_HALO},
        "radius": {"block": T.R_BLOCK, "panel": T.R_PANEL},
        "dash": {"soft": T.DASH_SOFT, "leader": T.DOT_LEADER},
        "space": {"gap": T.GAP, "padBlockX": T.PAD_BLOCK_X,
                  "padBlockY": T.PAD_BLOCK_Y, "padPanel": T.PAD_PANEL,
                  "padCanvas": T.PAD_CANVAS},
        "widths": {"narrow": T.W_NARROW, "medium": T.W_MEDIUM,
                   "column": T.W_COLUMN, "wide": T.W_WIDE},
    }


def main() -> None:
    data = as_dict()

    json_path = os.path.join(REPO_ROOT, "tools", "figstyle", "tokens.json")
    with open(json_path, "w") as fh:
        json.dump(data, fh, indent=2, sort_keys=True)
        fh.write("\n")
    print("wrote", json_path)

    mjs_path = os.path.join(REPO_ROOT, "diagrams", "tokens.mjs")
    lines = [
        "// GENERATED by tools/figstyle/export.py — do not edit by hand.",
        "// Single source of truth: tools/figstyle/tokens.py",
        f"export const TOKENS = {json.dumps(data, indent=2, sort_keys=True)};",
        "",
        "// Back-compat aliases matching diagrams/engine.mjs's old C object:",
        "export const C = {",
        f"  blue: '{T.BLUE.base}', lblue: '{T.BLUE.tint}',",
        f"  amber: '{T.ORANGE.base}', lamber: '{T.ORANGE.tint}',",
        f"  green: '{T.GREEN.base}', lgreen: '{T.GREEN.tint}',",
        f"  purple: '{T.PURPLE.base}', gray: '{T.MUTED}',",
        f"  lgray: '{T.PANEL}', ink: '{T.INK}', muted: '{T.MUTED}',",
        "};",
    ]
    with open(mjs_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", mjs_path)


if __name__ == "__main__":
    main()
