
# Documentation
::: {.panel-tabset group="framework"}

## PyTorch

While we cannot possibly introduce every single PyTorch function and class 
(and the information might become outdated quickly), 
the [API documentation](https://pytorch.org/docs/stable/index.html) and additional [tutorials](https://pytorch.org/tutorials/beginner/basics/intro.html) and examples 
provide such documentation.
This section provides some guidance for how to explore the PyTorch API.

## TensorFlow

While we cannot possibly introduce every single TensorFlow function and class 
(and the information might become outdated quickly), 
the [API documentation](https://www.tensorflow.org/api_docs) and additional [tutorials](https://www.tensorflow.org/tutorials) and examples 
provide such documentation. 
This section provides some guidance for how to explore the TensorFlow API.

## MXNet

While we cannot possibly introduce every single MXNet function and class 
(and the information might become outdated quickly), 
the [API documentation](https://mxnet.apache.org/versions/1.8.0/api) 
and additional [tutorials](https://mxnet.apache.org/versions/1.8.0/api/python/docs/tutorials/) and examples 
provide such documentation. 
This section provides some guidance for how to explore the MXNet API.

:::


::: {.panel-tabset group="framework"}


## PyTorch

```{python}
import torch
```


## TensorFlow

```python
import tensorflow as tf
```


## JAX

```python
import jax
```


## MXNet

```python
from mxnet import np
```


:::


## Functions and Classes in a Module

To know which functions and classes can be called in a module,
we invoke the `dir` function. For instance, we can
query all properties in the module for generating random numbers:


::: {.panel-tabset group="framework"}


## PyTorch

```{python}
print(dir(torch.distributions))
```


## TensorFlow

```python
print(dir(tf.random))
```


## JAX

```python
print(dir(jax.random))
```


## MXNet

```python
print(dir(np.random))
```


:::


Generally, we can ignore functions that start and end with `__` (special objects in Python) 
or functions that start with a single `_`(usually internal functions). 
Based on the remaining function or attribute names, 
we might hazard a guess that this module offers 
various methods for generating random numbers, 
including sampling from the uniform distribution (`uniform`), 
normal distribution (`normal`), and multinomial distribution (`multinomial`).

## Specific Functions and Classes

For specific instructions on how to use a given function or class,
we can invoke the  `help` function. As an example, let's
explore the usage instructions for tensors' `ones` function.


::: {.panel-tabset group="framework"}


## PyTorch

```{python}
help(torch.ones)
```


## TensorFlow

```python
help(tf.ones)
```


## JAX

```python
help(jax.numpy.ones)
```


## MXNet

```python
help(np.ones)
```


:::


From the documentation, we can see that the `ones` function 
creates a new tensor with the specified shape 
and sets all the elements to the value of 1. 
Whenever possible, you should run a quick test 
to confirm your interpretation:


::: {.panel-tabset group="framework"}


## PyTorch

```{python}
torch.ones(4)
```


## TensorFlow

```python
tf.ones(4)
```


## JAX

```python
jax.numpy.ones(4)
```


## MXNet

```python
np.ones(4)
```


:::


In the Jupyter notebook, we can use `?` to display the document in another
window. For example, `list?` will create content
that is almost identical to `help(list)`,
displaying it in a new browser window.
In addition, if we use two question marks, such as `list??`,
the Python code implementing the function will also be displayed.

The official documentation provides plenty of descriptions and examples that are beyond this book. 
We emphasize important use cases 
that will get you started quickly with practical problems, 
rather than completeness of coverage. 
We also encourage you to study the source code of the libraries 
to see examples of high-quality implementations of production code. 
By doing this you will become a better engineer 
in addition to becoming a better scientist.

::: {.panel-tabset group="framework"}

## PyTorch

[Discussions](https://discuss.d2l.ai/t/39)

## TensorFlow

[Discussions](https://discuss.d2l.ai/t/199)

## JAX

[Discussions](https://discuss.d2l.ai/t/17972)

## MXNet

[Discussions](https://discuss.d2l.ai/t/38)

:::

