// GENERATED by tools/figstyle/export.py — do not edit by hand.
// Single source of truth: tools/figstyle/tokens.py
export const TOKENS = {
  "accents": {
    "blue": {
      "base": "#1565C0",
      "dark": "#094F86",
      "tint": "#D6EDFC"
    },
    "gold": {
      "base": "#9A7212",
      "dark": "#6E5108",
      "tint": "#FBF2D4"
    },
    "green": {
      "base": "#2E7D3E",
      "dark": "#1F5C2C",
      "tint": "#DDF0DD"
    },
    "orange": {
      "base": "#B45309",
      "dark": "#7F3B06",
      "tint": "#FBE8D3"
    },
    "purple": {
      "base": "#6C51B4",
      "dark": "#503B8C",
      "tint": "#EDE9F8"
    },
    "red": {
      "base": "#C03B2F",
      "dark": "#93261C",
      "tint": "#FBE7E4"
    },
    "slate": {
      "base": "#565D66",
      "dark": "#15181C",
      "tint": "#F0F2F5"
    },
    "teal": {
      "base": "#1F7D74",
      "dark": "#145A53",
      "tint": "#DEF1EF"
    }
  },
  "cycle": [
    "#1565C0",
    "#B45309",
    "#2E7D3E",
    "#6C51B4",
    "#C03B2F",
    "#1F7D74",
    "#9A7212",
    "#565D66"
  ],
  "dash": {
    "leader": "1.5 2.5",
    "soft": "4 3"
  },
  "neutrals": {
    "containerFill": "#E4E4E4",
    "faint": "#8F98A1",
    "hairline": "#D9DEE4",
    "ink": "#15181C",
    "insetFill": "#ECECEC",
    "muted": "#565D66",
    "noveltyFill": "#3B3B3B",
    "panel": "#F0F2F5",
    "paper": "#FFFFFF"
  },
  "radius": {
    "block": 6.0,
    "panel": 12.0
  },
  "roles": {
    "attention": "orange",
    "embed": "purple",
    "ffn": "green",
    "grad": "red",
    "highlight": "gold",
    "norm": "slate",
    "params": "slate",
    "state": "teal",
    "stream": "blue"
  },
  "space": {
    "gap": 8.0,
    "padBlockX": 15.0,
    "padBlockY": 9.0,
    "padCanvas": 6.0,
    "padPanel": 14.0
  },
  "stroke": {
    "box": 2.0,
    "hair": 1.5,
    "halo": 10.0,
    "heavy": 4.0,
    "line": 2.5
  },
  "type": {
    "label": 17.0,
    "letterspaceCaps": 0.08,
    "min": 12.0,
    "mono": "Inconsolata",
    "sans": "Source Sans 3",
    "small": 14.5,
    "tiny": 13.0,
    "title": 19.0
  },
  "widths": {
    "column": 720.0,
    "medium": 560.0,
    "narrow": 420.0,
    "wide": 960.0
  }
};

// Back-compat aliases matching diagrams/engine.mjs's old C object:
export const C = {
  blue: '#1565C0', lblue: '#D6EDFC',
  amber: '#B45309', lamber: '#FBE8D3',
  green: '#2E7D3E', lgreen: '#DDF0DD',
  purple: '#6C51B4', gray: '#565D66',
  lgray: '#F0F2F5', ink: '#15181C', muted: '#565D66',
};
