#!/usr/bin/env python3
"""Post-process LaTeX generated by Quarto for the d2l book.

Converts flat chapter structure into hierarchical chapters/sections,
unnumbers frontmatter, sets page numbering, fixes appendix numbering.

Usage:
    python tools/fix_latex.py <tex_file>
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from d2l_preprocess import CHAPTER_NUMBERING, PDF_CHAPTER_FILES


# References into pages that exist only in the HTML edition (the
# PDF_EXCLUDED_FILES reference pages). Quarto renders a :numref: to an
# absent target as a literal bold "?@sec-..." marker; rewrite the known
# ones into prose that degrades gracefully in print. Any *other* residual
# "?@" marker is a genuine broken reference — warn loudly so it is caught
# at build time instead of shipping.
HTML_ONLY_REFS = {
    'sec-utils': 'the utility reference of the online edition',
    'sec-d2l': 'the d2l API reference of the online edition',
}


def fix_html_only_refs(content):
    for target, wording in HTML_ONLY_REFS.items():
        for pat in (r'\textbf{?@%s}' % target, '?@%s' % target):
            if pat in content:
                n = content.count(pat)
                content = content.replace(pat, wording)
                print(f'  Rewrote {n} reference(s) to HTML-only {target}')
    residual = sorted(set(re.findall(r'\?@[a-z0-9-]+', content)))
    if residual:
        print(f'  WARNING: unresolved crossrefs remain in the PDF: '
              f'{", ".join(residual)}')
    return content


def fix_all(content):
    content = fix_html_only_refs(content)
    files = [(rel, CHAPTER_NUMBERING[rel]) for rel in PDF_CHAPTER_FILES]

    # Find all \chapter{...} with optional \label{...}
    chapter_re = re.compile(r'\\chapter\{[^}]+\}(?:\\label\{[^}]+\})?')
    matches = list(chapter_re.finditer(content))
    print(f'  Found {len(matches)} \\chapter commands, {len(files)} NUMBERING entries')

    # ── Phase 1: Mark each \chapter with its logical role ──
    # Build (match, role, logical) tuples
    # Role: 'landing', 'frontmatter', 'chapter', 'section', 'references'
    tagged = []
    for i, m in enumerate(matches):
        if i == 0:
            tagged.append((m, 'landing', None))
            continue
        file_idx = i - 1
        if file_idx >= len(files):
            # References or extra
            title = re.search(r'\\chapter\{([^}]+)\}', m.group()).group(1)
            if 'References' in title:
                tagged.append((m, 'references', None))
            else:
                tagged.append((m, 'extra', None))
            continue
        _, logical = files[file_idx]
        if logical is None:
            tagged.append((m, 'frontmatter', None))
        elif len(logical) == 1:
            tagged.append((m, 'chapter', logical))
        else:
            tagged.append((m, 'section', logical))

    # ── Phase 2: Apply replacements (reverse order for stable offsets) ──
    for i in range(len(tagged) - 1, -1, -1):
        m, role, logical = tagged[i]
        start, end = m.start(), m.end()
        original = m.group()
        title_m = re.search(r'\\chapter\{([^}]+)\}', original)
        title = title_m.group(1) if title_m else ''
        label_m = re.search(r'\\label\{[^}]+\}', original)
        label = label_m.group() if label_m else ''

        if role == 'landing':
            content = content[:start] + '% landing page removed' + content[end:]

        elif role == 'frontmatter':
            new = (f'\\chapter*{{{title}}}'
                   f'\\addcontentsline{{toc}}{{chapter}}{{{title}}}{label}')
            content = content[:start] + new + content[end:]

        elif role == 'chapter':
            ch = logical[0]
            new = f'\\setcounter{{chapter}}{{{ch - 1}}}\n{original}'
            content = content[:start] + new + content[end:]

        elif role == 'section':
            # Mark with %D2L-FILE-SECTION so Phase 3 can demote inner headings
            new = f'%D2L-FILE-SECTION\n\\section{{{title}}}{label}'
            content = content[:start] + new + content[end:]

        elif role == 'references':
            new = (f'\\chapter*{{{title}}}'
                   f'\\addcontentsline{{toc}}{{chapter}}{{{title}}}{label}')
            content = content[:start] + new + content[end:]

    # ── Phase 3: Demote headings inside file-level sections ──
    # State machine:
    #   'normal' → not inside a file-section, don't demote
    #   'skip_next' → just saw marker, next \section is the file-level heading (keep it)
    #   'demoting' → inside file-section content, demote \section→\subsection etc.
    lines = content.split('\n')
    state = 'normal'

    for i, l in enumerate(lines):
        if l.strip() == '%D2L-FILE-SECTION':
            state = 'skip_next'
            lines[i] = ''
            continue

        # Chapter boundaries end demotion
        if state == 'demoting' and (
            l.startswith('\\setcounter{chapter}') or
            l.startswith('\\chapter{') or
            l.startswith('\\chapter*{') or
            l.startswith('\\appendix')
        ):
            state = 'normal'

        if state == 'skip_next':
            # This line is the file-level \section{} — keep it, start demoting after
            state = 'demoting'
            continue

        if state == 'demoting':
            if l.startswith('\\subsubsection{'):
                lines[i] = l.replace('\\subsubsection{', '\\paragraph{', 1)
            elif l.startswith('\\subsection{'):
                lines[i] = l.replace('\\subsection{', '\\subsubsection{', 1)
            elif l.startswith('\\section{'):
                lines[i] = l.replace('\\section{', '\\subsection{', 1)

    content = '\n'.join(lines)

    # ── Phase 4: Fix frontmatter section numbering ──
    # Sections inside \chapter*{} (unnumbered chapters) should also be unnumbered.
    # Find ranges of unnumbered chapters and star their sections.
    lines = content.split('\n')
    in_unnumbered = False
    for i, l in enumerate(lines):
        if l.startswith('\\chapter*{'):
            in_unnumbered = True
        elif l.startswith('\\chapter{') or l.startswith('\\setcounter{chapter}'):
            in_unnumbered = False
        elif in_unnumbered:
            for cmd in ['\\subsubsection{', '\\subsection{', '\\section{']:
                if l.startswith(cmd):
                    lines[i] = l.replace(cmd, cmd.replace('{', '*{'), 1)
                    break
    content = '\n'.join(lines)

    # Cross-references to unnumbered frontmatter must use their titles. A
    # numeric \ref is undefined for \chapter* and can otherwise inherit the
    # preceding chapter counter.
    frontmatter_refs = {
        'sec-chap-installation': 'Installation',
        'sec-chap-notation': 'Notation',
        'sec-chap-introduction': 'Introduction',
    }
    for label, title in frontmatter_refs.items():
        content = content.replace(
            f'Chapter~\\ref{{{label}}}', f'\\hyperref[{label}]{{{title}}}')

    # ── Phase 5: Page numbering ──
    content = content.replace(
        '\\begin{document}',
        '\\begin{document}\n\\pagenumbering{roman}', 1)

    first_chapter = re.search(
        r'\\setcounter\{chapter\}\{0\}\n\\chapter\{Preliminaries\}', content)
    if first_chapter:
        content = (content[:first_chapter.start()] +
                  '\\pagenumbering{arabic}\\setcounter{page}{1}\n' +
                  content[first_chapter.start():])

    # ── Phase 6: Appendix ──
    # The "Mathematics for Deep Learning" appendix (logical chapters 21+)
    # renders with \appendix lettering (A, B, C, …), sections nested (A.1…).
    # Phase 2 gave each appendix chapter \setcounter{chapter}{ch-1}; under
    # \appendix we want them counted from 0 (→A), so remap every appendix
    # counter N>=20 → N-20 (21→A, 22→B, 23→C, …).
    first_app = re.search(r'\\setcounter\{chapter\}\{20\}', content)
    if first_app:
        idx = first_app.start()
        head, tail = content[:idx], content[idx:]

        def _shift_appendix(m):
            n = int(m.group(1))
            return f'\\setcounter{{chapter}}{{{n - 20}}}' if n >= 20 else m.group(0)

        tail = re.sub(r'\\setcounter\{chapter\}\{(\d+)\}', _shift_appendix, tail)
        content = head + '\\appendix\n' + tail

    # ── Phase 7: Remove the "X" empty chapter (from zreferences) ──
    content = re.sub(r'\\chapter\{\\texorpdfstring[^}]*\}[^\n]*\n', '', content)

    # ── Phase 8: TOC depth ──
    # Set depth to 2 so sections within chapters show in TOC
    content = content.replace('\\setcounter{tocdepth}{1}', '\\setcounter{tocdepth}{2}')

    # ── Phase 9: Special chars ──
    lines = content.split('\n')
    for i, l in enumerate(lines):
        for cmd in ['\\chapter{', '\\chapter*{', '\\section{', '\\subsection{',
                    '\\subsubsection{', '\\caption{']:
            if l.startswith(cmd):
                lines[i] = l.replace('\u2018', "'").replace('\u2019', "'")
                lines[i] = lines[i].replace('\u201c', '``').replace('\u201d', "''")
                lines[i] = lines[i].replace('\u2013', '--').replace('\u2014', '---')
                break
    content = '\n'.join(lines)

    # ── Phase 10: Remove landing page content ──
    # The "An interactive deep learning book..." line
    content = re.sub(
        r'An interactive deep learning book with code, math, and discussions\.',
        '', content)

    return content


def main():
    if len(sys.argv) < 2:
        print("Usage: python fix_latex.py <tex_file>")
        sys.exit(1)

    tex_file = sys.argv[1]
    with open(tex_file) as f:
        content = f.read()

    print(f'Post-processing {tex_file}...')
    content = fix_all(content)

    with open(tex_file, 'w') as f:
        f.write(content)

    n_ch = len(re.findall(r'\\chapter\{', content))
    n_star = len(re.findall(r'\\chapter\*\{', content))
    n_sec = content.count('\\section{')
    n_subsec = content.count('\\subsection{')
    print(f'  Chapters: {n_ch} numbered, {n_star} unnumbered')
    print(f'  Sections: {n_sec}, Subsections: {n_subsec}')
    print(f'  Done.')


if __name__ == '__main__':
    main()
