#!/usr/bin/env python3
"""Post-process LaTeX generated by Quarto for the d2l book.

Converts flat chapter structure into hierarchical chapters/sections,
unnumbers frontmatter, sets page numbering, fixes appendix numbering.

Usage:
    python tools/fix_latex.py <tex_file>
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from d2l_preprocess import CHAPTER_NUMBERING


def fix_all(content):
    files = list(CHAPTER_NUMBERING.items())

    # Find all \chapter{...} with optional \label{...}
    chapter_re = re.compile(r'\\chapter\{[^}]+\}(?:\\label\{[^}]+\})?')
    matches = list(chapter_re.finditer(content))
    print(f'  Found {len(matches)} \\chapter commands, {len(files)} NUMBERING entries')

    # ── Phase 1: Mark each \chapter with its logical role ──
    # Build (match, role, logical) tuples
    # Role: 'landing', 'frontmatter', 'chapter', 'section', 'references'
    tagged = []
    for i, m in enumerate(matches):
        if i == 0:
            tagged.append((m, 'landing', None))
            continue
        file_idx = i - 1
        if file_idx >= len(files):
            # References or extra
            title = re.search(r'\\chapter\{([^}]+)\}', m.group()).group(1)
            if 'References' in title:
                tagged.append((m, 'references', None))
            else:
                tagged.append((m, 'extra', None))
            continue
        _, logical = files[file_idx]
        if logical is None:
            tagged.append((m, 'frontmatter', None))
        elif len(logical) == 1:
            tagged.append((m, 'chapter', logical))
        else:
            tagged.append((m, 'section', logical))

    # ── Phase 2: Apply replacements (reverse order for stable offsets) ──
    for i in range(len(tagged) - 1, -1, -1):
        m, role, logical = tagged[i]
        start, end = m.start(), m.end()
        original = m.group()
        title_m = re.search(r'\\chapter\{([^}]+)\}', original)
        title = title_m.group(1) if title_m else ''
        label_m = re.search(r'\\label\{[^}]+\}', original)
        label = label_m.group() if label_m else ''

        if role == 'landing':
            content = content[:start] + '% landing page removed' + content[end:]

        elif role == 'frontmatter':
            new = (f'\\chapter*{{{title}}}'
                   f'\\addcontentsline{{toc}}{{chapter}}{{{title}}}{label}')
            content = content[:start] + new + content[end:]

        elif role == 'chapter':
            ch = logical[0]
            new = f'\\setcounter{{chapter}}{{{ch - 1}}}\n{original}'
            content = content[:start] + new + content[end:]

        elif role == 'section':
            # Mark with %D2L-FILE-SECTION so Phase 3 can demote inner headings
            new = f'%D2L-FILE-SECTION\n\\section{{{title}}}{label}'
            content = content[:start] + new + content[end:]

        elif role == 'references':
            new = (f'\\chapter*{{{title}}}'
                   f'\\addcontentsline{{toc}}{{chapter}}{{{title}}}{label}')
            content = content[:start] + new + content[end:]

    # ── Phase 3: Demote headings inside file-level sections ──
    # State machine:
    #   'normal' → not inside a file-section, don't demote
    #   'skip_next' → just saw marker, next \section is the file-level heading (keep it)
    #   'demoting' → inside file-section content, demote \section→\subsection etc.
    lines = content.split('\n')
    state = 'normal'

    for i, l in enumerate(lines):
        if l.strip() == '%D2L-FILE-SECTION':
            state = 'skip_next'
            lines[i] = ''
            continue

        # Chapter boundaries end demotion
        if state == 'demoting' and (
            l.startswith('\\setcounter{chapter}') or
            l.startswith('\\chapter{') or
            l.startswith('\\chapter*{') or
            l.startswith('\\appendix')
        ):
            state = 'normal'

        if state == 'skip_next':
            # This line is the file-level \section{} — keep it, start demoting after
            state = 'demoting'
            continue

        if state == 'demoting':
            if l.startswith('\\subsubsection{'):
                lines[i] = l.replace('\\subsubsection{', '\\paragraph{', 1)
            elif l.startswith('\\subsection{'):
                lines[i] = l.replace('\\subsection{', '\\subsubsection{', 1)
            elif l.startswith('\\section{'):
                lines[i] = l.replace('\\section{', '\\subsection{', 1)

    content = '\n'.join(lines)

    # ── Phase 4: Fix frontmatter section numbering ──
    # Sections inside \chapter*{} (unnumbered chapters) should also be unnumbered.
    # Find ranges of unnumbered chapters and star their sections.
    lines = content.split('\n')
    in_unnumbered = False
    for i, l in enumerate(lines):
        if l.startswith('\\chapter*{'):
            in_unnumbered = True
        elif l.startswith('\\chapter{') or l.startswith('\\setcounter{chapter}'):
            in_unnumbered = False
        elif in_unnumbered:
            for cmd in ['\\subsubsection{', '\\subsection{', '\\section{']:
                if l.startswith(cmd):
                    lines[i] = l.replace(cmd, cmd.replace('{', '*{'), 1)
                    break
    content = '\n'.join(lines)

    # ── Phase 5: Page numbering ──
    content = content.replace(
        '\\begin{document}',
        '\\begin{document}\n\\pagenumbering{roman}', 1)

    intro_m = re.search(r'\\setcounter\{chapter\}\{0\}\n\\chapter\{Introduction\}', content)
    if intro_m:
        content = (content[:intro_m.start()] +
                  '\\pagenumbering{arabic}\\setcounter{page}{1}\n' +
                  content[intro_m.start():])

    # ── Phase 6: Appendix ──
    # Find the first appendix chapter (ch 22 = "Mathematics for Deep Learning")
    app_m = re.search(r'\\setcounter\{chapter\}\{21\}', content)
    if app_m:
        content = (content[:app_m.start()] +
                  '\\appendix\\setcounter{chapter}{0}\n' +
                  content[app_m.start():])
        # Fix the setcounter values for appendix chapters
        content = content.replace('\\setcounter{chapter}{21}', '\\setcounter{chapter}{0}')
        content = content.replace('\\setcounter{chapter}{22}', '\\setcounter{chapter}{1}')

    # ── Phase 7: Remove the "X" empty chapter (from zreferences) ──
    content = re.sub(r'\\chapter\{\\texorpdfstring[^}]*\}[^\n]*\n', '', content)

    # ── Phase 8: TOC depth ──
    # Set depth to 2 so sections within chapters show in TOC
    content = content.replace('\\setcounter{tocdepth}{1}', '\\setcounter{tocdepth}{2}')

    # ── Phase 9: Special chars ──
    lines = content.split('\n')
    for i, l in enumerate(lines):
        for cmd in ['\\chapter{', '\\chapter*{', '\\section{', '\\subsection{',
                    '\\subsubsection{', '\\caption{']:
            if l.startswith(cmd):
                lines[i] = l.replace('\u2018', "'").replace('\u2019', "'")
                lines[i] = lines[i].replace('\u201c', '``').replace('\u201d', "''")
                lines[i] = lines[i].replace('\u2013', '--').replace('\u2014', '---')
                break
    content = '\n'.join(lines)

    # ── Phase 10: Remove landing page content ──
    # The "An interactive deep learning book..." line
    content = re.sub(
        r'An interactive deep learning book with code, math, and discussions\.',
        '', content)

    return content


def main():
    if len(sys.argv) < 2:
        print("Usage: python fix_latex.py <tex_file>")
        sys.exit(1)

    tex_file = sys.argv[1]
    with open(tex_file) as f:
        content = f.read()

    print(f'Post-processing {tex_file}...')
    content = fix_all(content)

    with open(tex_file, 'w') as f:
        f.write(content)

    n_ch = len(re.findall(r'\\chapter\{', content))
    n_star = len(re.findall(r'\\chapter\*\{', content))
    n_sec = content.count('\\section{')
    n_subsec = content.count('\\subsection{')
    print(f'  Chapters: {n_ch} numbered, {n_star} unnumbered')
    print(f'  Sections: {n_sec}, Subsections: {n_subsec}')
    print(f'  Done.')


if __name__ == '__main__':
    main()
