#!/usr/bin/env python3
"""Render the university logo grid in index.md from tools/universities.json.

Replaces content between the markers
    <!-- @universities-begin ... -->
    <!-- @universities-end -->
in index.md (and index.qmd if present, though the latter is auto-generated).

Each university is rendered as either:
  <a href="<course_url>" title="..."><img src="..." alt="..." loading="lazy"></a>
when course evidence exists, or a plain <img> otherwise.

Usage:
    python tools/render_logo_grid.py
"""
import html
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
JSON_PATH = REPO / "tools" / "universities.json"
LOGO_REL_DIR = "static/landing/universities"

BEGIN = "<!-- @universities-begin"
END = "<!-- @universities-end -->"
INDENT = " " * 6


def is_weak_evidence(url: str) -> bool:
    """Skip URLs that aren't independent course evidence."""
    if not url:
        return True
    u = url.lower().rstrip("/")
    # The d2l.ai homepage adopters list is self-attested, not independent.
    if u in {"https://d2l.ai", "https://www.d2l.ai", "http://d2l.ai", "http://www.d2l.ai"}:
        return True
    if u.startswith("https://classic.d2l.ai") or u.startswith("http://classic.d2l.ai"):
        return True
    if u.startswith("https://d2l.ai/#") or u.startswith("https://www.d2l.ai/#"):
        return True
    # Studocu/coursehero/scribd are paywalled aggregators, not the institution's own page.
    if "studocu.com" in u or "coursehero.com" in u or "scribd.com" in u:
        return True
    return False


def pick_link(evidence: list) -> dict | None:
    """Choose the strongest evidence URL — first non-weak entry by year-desc order."""
    for ev in evidence:
        if not is_weak_evidence(ev.get("url", "")):
            return ev
    return None


def render_grid(entries: list) -> str:
    lines = []
    lines.append(f"{INDENT}<!-- @universities-begin (auto-generated by tools/render_logo_grid.py from tools/universities.json) -->")
    for e in entries:
        if not e.get("logo"):
            continue
        src = f"{LOGO_REL_DIR}/{e['logo']}"
        alt = html.escape(e["name"])
        # Logos that are white-on-transparent disappear against the
        # white landing page — universities.json carries an `invert`
        # flag for those; emit a CSS hook here.
        img_class = ' class="d2l-uni-logo-invert"' if e.get("invert") else ""
        link_ev = pick_link(e.get("evidence") or [])
        if link_ev:
            url = link_ev["url"]
            course = link_ev.get("course") or ""
            instructor = link_ev.get("instructor") or ""
            title_parts = [e["name"]]
            if course:
                title_parts.append(course)
            if instructor:
                title_parts.append(instructor)
            title = html.escape(" — ".join(title_parts))
            href = html.escape(url, quote=True)
            lines.append(
                f'{INDENT}<a href="{href}" title="{title}" target="_blank" rel="noopener">'
                f'<img src="{src}"{img_class} alt="{alt}" loading="lazy"></a>'
            )
        else:
            lines.append(f'{INDENT}<img src="{src}"{img_class} alt="{alt}" loading="lazy">')
    lines.append(f"{INDENT}{END}")
    return "\n".join(lines)


def replace_block(text: str, new_block: str) -> str:
    """Replace the block between BEGIN-line and END marker (inclusive)."""
    # Match from a line containing BEGIN to a line containing END (inclusive of both lines).
    pattern = re.compile(
        rf"^[ \t]*{re.escape('<!-- @universities-begin')}.*?{re.escape(END)}[ \t]*$",
        re.M | re.S,
    )
    if not pattern.search(text):
        raise SystemExit(
            "could not find @universities-begin/@universities-end markers in target file"
        )
    return pattern.sub(new_block.strip(), text, count=1)


def main():
    entries = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    block = render_grid(entries)
    rendered_count = block.count("<img ")

    targets = [REPO / "index.md"]
    # index.qmd is regenerated by d2l_preprocess.py, but if it has the markers we sync it too.
    qmd = REPO / "index.qmd"
    if qmd.exists() and "@universities-begin" in qmd.read_text(encoding="utf-8"):
        targets.append(qmd)

    for path in targets:
        text = path.read_text(encoding="utf-8")
        new_text = replace_block(text, block)
        if new_text != text:
            path.write_text(new_text, encoding="utf-8")
            print(f"updated {path}  ({rendered_count} <img> tags)")
        else:
            print(f"unchanged {path}")


if __name__ == "__main__":
    main()
