#!/usr/bin/env python3
"""Scan source .md files and emit per-framework MANIFEST.mk for the Makefile.

A "manifest" lists every per-notebook .executed stamp that the framework
will produce. Built without invoking the full gen_notebooks.py pipeline so
Make can call this during -include parsing cheaply (~1s for the whole tree
vs ~30s per framework for full notebook generation).

Detection is purely textual: a source file `chapter_x/foo.md` produces
`_notebooks/<fw>/chapter_x/foo.ipynb` iff it contains a `#@tab <fw>` or
`%%tab <fw>` marker (with `all` matching every framework).

Usage:
    python tools/scan_notebook_manifests.py --output-dir _notebooks
"""
import argparse
import re
import sys
from pathlib import Path

from runtime_env import GPU_KEYWORDS, MULTI_GPU_NOTEBOOKS


FRAMEWORKS = ('pytorch', 'tensorflow', 'jax', 'mxnet')
TAB_RE = re.compile(r'^(?:%%tab|#@tab)\s+([^\n]+)$', re.MULTILINE)
SELECT_RE = re.compile(r'tab\.interact_select\(([^)]+)\)')
PY_BLOCK_RE = re.compile(r'```\{\.python')


def file_frameworks(md_path):
    """Return frameworks for which md_path should produce a notebook.

    Mirrors tools/gen_notebooks.py:file_supports_framework so the manifest
    matches what the generator actually emits:
      1. explicit `#@tab X` / `%%tab X` (with `all` matching every fw),
      2. tab.interact_select listing X,
      3. files with code but NO framework-specific tags fall through to
         pytorch only (matches the d2l-en convention).
    """
    try:
        text = md_path.read_text(encoding='utf-8')
    except Exception:
        return set()

    found = set()
    has_any_specific = False
    for m in TAB_RE.finditer(text):
        fws = [t.strip() for t in m.group(1).split(',')]
        if 'all' in fws:
            for fw in FRAMEWORKS:
                found.add(fw)
        else:
            for fw in fws:
                if fw in FRAMEWORKS:
                    found.add(fw)
                    has_any_specific = True

    for m in SELECT_RE.finditer(text):
        fws = re.findall(r"['\"](\w+)['\"]", m.group(1))
        for fw in fws:
            if fw in FRAMEWORKS:
                found.add(fw)
                has_any_specific = True

    # Files with code but no framework-specific tag → pytorch-only.
    if not has_any_specific and PY_BLOCK_RE.search(text):
        found.add('pytorch')

    return found


def notebook_rel(rel):
    """Return the notebook-relative path produced from a source-relative path."""
    return rel.with_suffix('.ipynb').as_posix()


def source_execution_class(md_path, rel):
    """Classify the notebook produced from *md_path* as cpu/gpu/multi-gpu.

    The Make-visible manifest is generated before notebooks necessarily
    exist, so this mirrors runtime classification with a source-level scan.
    `file_uses_gpu()` also treats sibling framework notebooks as GPU-using if
    any sibling uses a GPU; scanning the shared source file gives the same
    conservative behavior for all frameworks produced from the file.
    """
    if notebook_rel(rel) in MULTI_GPU_NOTEBOOKS:
        return 'multi-gpu'
    try:
        text = md_path.read_text(encoding='utf-8')
    except Exception:
        text = ''
    if any(kw in text for kw in GPU_KEYWORDS):
        return 'gpu'
    return 'cpu'


def _write_if_changed(path, content):
    if path.exists() and path.read_bytes() == content:
        return False
    path.write_bytes(content)
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--source', type=Path, default=Path('.'),
                        help='Source directory (default: cwd)')
    parser.add_argument('--output-dir', type=Path, default=Path('_notebooks'),
                        help='Destination _notebooks dir')
    args = parser.parse_args()

    # Per-framework: list of relative source .md paths it produces, split by
    # resource class so Make can admit CPU and GPU jobs independently.
    per_fw = {fw: {'all': [], 'cpu': [], 'gpu': [], 'multi-gpu': []}
              for fw in FRAMEWORKS}
    for md in sorted(args.source.glob('chapter_*/*.md')):
        rel = md.relative_to(args.source)
        mode = source_execution_class(md, rel)
        for fw in file_frameworks(md):
            per_fw[fw]['all'].append(rel)
            per_fw[fw][mode].append(rel)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    for fw, sources_by_mode in per_fw.items():
        fw_dir = args.output_dir / fw
        fw_dir.mkdir(parents=True, exist_ok=True)
        # Per-notebook stamps. Match gen_notebooks.py output naming:
        # source chapter_x/foo.md → _notebooks/<fw>/chapter_x/foo.ipynb
        stamp_lists = {
            name: [str((fw_dir / rel).with_suffix('.executed'))
                   for rel in rels]
            for name, rels in sources_by_mode.items()
        }
        lines = [
            '# Auto-generated by tools/scan_notebook_manifests.py — do not edit.',
            f'EXECUTED_{fw} := ' + ' '.join(stamp_lists['all']),
            f'EXECUTED_CPU_{fw} := ' + ' '.join(stamp_lists['cpu']),
            f'EXECUTED_GPU_{fw} := ' + ' '.join(stamp_lists['gpu']),
            f'EXECUTED_MULTI_GPU_{fw} := ' + ' '.join(stamp_lists['multi-gpu']),
        ]
        content = ('\n'.join(lines) + '\n').encode('utf-8')
        path = fw_dir / 'MANIFEST.mk'
        if _write_if_changed(path, content):
            print(f'  updated {path} ({len(stamp_lists["all"])} notebooks: '
                  f'{len(stamp_lists["gpu"])} GPU, '
                  f'{len(stamp_lists["cpu"])} CPU, '
                  f'{len(stamp_lists["multi-gpu"])} multi-GPU)')


if __name__ == '__main__':
    main()
